spring:
  main:
    web-application-type: none   # CLIモード
  output:
    ansi:
      enabled: DETECT

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger - %msg%n"
