name: Build and Test
on:
  push:
    branches: [ main, develop, "feature/**", "feat/**" ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Build & Test
        run: ./mvnw -B -DskipTests=false clean verify
